name: shopflooraudit
description: A Flutter application for the questionnaire.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1       # Or latest version
  path_provider: ^2.0.11       # Or latest version
  share_plus: ^6.3.0           # Or latest version
  intl: ^0.17.0                # for date formatting
  firebase_analytics: ^11.4.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true